---
- name: Playbook for OpenShift Virt
  hosts: localhost
  tasks:

  - name: Place a change request in ServiceNow in Review
    servicenow.itsm.change_request:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
      state: review
      number: "{{ request.record.number }}"
    delegate_to: localhost

  - name: Close a change request
    servicenow.itsm.change_request:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
      state: closed
      number: "{{ request.record.number }}"
      close_code: "{{ close_code }}"
      close_notes: "{{ user_selected_vm_names }} VM(s) have been migrated successfully!!"
    delegate_to: localhost