---
- name: Playbook for OpenShift Virt Post Migration Validation
  hosts: all
  gather_facts: false
  tasks:

    - name: Ping Test for Windows
      ansible.windows.win_ping:
      when: '"windows" in config.guestId'

    - name: Ping Test for Linux
      ansible.builtin.ping:
      when: '"Linux" in config.guestId'

    - name: Ping Test for CentOS
      ansible.builtin.ping:
      when: '"centos" in config.guestId'
