---
- name: Playbook for OpenShift Virt Post Migration Validation
  hosts: all
  gather_facts: false
  tasks:

    - name: Debug
      debug:
        var: hostvars[inventory_hostname]

    - name: Set fact
      set_fact:
        my_hostvar: "{{ hostvars[inventory_hostname] }}"

    - name: Ping Test for Windows
      ansible.windows.win_ping:
      when: '"windows" in my_hostvar.config.guestId'

    - name: Ping Test for Linux
      ansible.builtin.ping:
      when: '"Linux" in my_hostvar.config.guestId'

    - name: Ping Test for CentOS
      ansible.builtin.ping:
      when: '"centos" in my_hostvar.config.guestId'
