---
- name: Playbook for Post Patching Tasks
  hosts: all
  gather_facts: false
  tasks:
    - name: Post Task Block
      block:
      - name: Ping Test for Linux
        ansible.builtin.ping:

      - name: Application Post Task
        include_tasks:
          file: application_tasks/post_task_{{ application_type | default('database') }}.yml
        register: result

      rescue:
      - name: Rescue for Failure
        debug:
          msg: "{{ result }} Demo has an issue atm!!"
