---
- name: Playbook for OpenShift Virt Pre Migration Validation
  hosts: localhost
  collections:
    - rlopez.ocp_virt

  pre_tasks:
    - name: Get kubeconfig
      debug: 
        msg: "{{ lookup('ansible.builtin.env', 'KUBECONFIG') }}"

  roles:
    - role: rlopez.ocp_virt.validation
      vars:
        cluster_name: "{{ vmware_cluster_name }}"
