---
- name: Playbook for OpenShift Virt
  hosts: localhost
  tasks:

  - name: Create change request
    servicenow.itsm.change_request:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"

      type: normal
      short_description: "{{ cr_short_description }}"
      description: "{{ tower_user_name }} requests {{ user_selected_vm_names }} VMs to migrate"
      priority: high
      impact: low
      assignment_group: VMware
      state: assess
      requested_by: "{{ tower_user_name }}"
    register: request
    until: request.changed is defined
    retries: 5
    delay: 5
    delegate_to: localhost

  - name: Send Approval e-mail
    community.general.mail:
      # host: "{{ EMAIL_HOST }}"
      # username: "{{ EMAIL_USERNAME }}"
      # password: "{{ EMAIL_PASSWORD }}"
      # port: "{{ EMAIL_PORT }}"
      subject: Approval request for ServiceNow Change Request {{ request.record.number }}
      body: "You have a new CR Approval request. Please click on this URL to approve: {{ servicenow_hostname }}nav_to.do?uri=change_request.do?sysparm_query=number={{request.record.number }}"
      from: tower@shadowman.dev
      to: "{{ to_email }}"
    delegate_to: localhost

  - name: Wait for Change Request approval
    servicenow.itsm.change_request_info:
      number: "{{ request.record.number }}"
    until: change_request_status.records[0].state == "scheduled"
    retries: 50
    delay: 10
    register: change_request_status
    delegate_to: localhost

  - name: Update to implement the change request in ServiceNow
    servicenow.itsm.change_request:
      state: implement
      number: "{{ request.record.number }}"
      assignment_group: VMware
    delegate_to: localhost